name: CI/CD
on: [push]
jobs:
  build-project:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v3
        with:
          node-version: '18.0.0'
      - name: Install dependencies
        run: npm install
      - name: Run all vite tests
        run: npm run test
      - name: build the production version
        run: npm run build
      - run: ls # List files in build directory for debugging
      - name: Zip build directory for deployment
        run: zip -r build.zip build  # Zip only the build directory
      - name: Upload artifact for deployment job
        uses: actions/upload-artifact@v3
        with:
          name: augur-app
          path: build.zip  
      # - name: Start the production app
      #   run: node build
  deploy-project:
    runs-on: ubuntu-latest
    needs: build-project
    environment:
      name: 'production'
      url: 'https://augur-frontend.azurewebsites.net/'
    steps:
      - name: Download artifact from build job
        uses: actions/download-artifact@v3
        with:
          name: augur-app
      - name: Unzip artifact for deployment
        run: unzip build.zip    
      - name: 'Deploy to Azure'
        id: deploy-to-webapp
        uses: azure/webapps-deploy@v2
        with:
          app-name: augur-frontend # Replace with your app name
          slot-name: 'production'
          publish-profile: ${{ secrets.AZURE_WEBAPP_PUBLISH_PROFILE }}
          package: build
