name: CI/CD
on: [push]
jobs:
  build-project:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v3
        with:
          node-version: '18.0.0'
      - name: Install dependencies
        run: npm install
      - name: Run all vite tests
        run: npm run test
      - name: build the production version
        run: npm run build
      # - run: ls  
      # - name: Zip artifact for deployment
      #   run: zip build.zip ./* -r  
    #   - name: Start the production app
    #     run: node build
      - name: 'Deploy to Azure'
        uses: azure/webapps-deploy@v2
        with:
          app-name: augur-frontend # Replace with your app name
          # slot-name: <Your-Slot-Name> # If you use slots
          publish-profile: ${{ secrets.AZURE_WEBAPP_PUBLISH_PROFILE }}
          package: build
